---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: 請參閱Astra Trident組態的可用組態選項。 
---
= 儲存組態選項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請參閱Astra Trident組態的可用組態選項。



== 全域組態選項

這些組態選項適用於所有Astra Trident組態、無論使用何種儲存平台。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| `version`  a| 
組態檔版本編號
 a| 
`1`



| `storageDriverName`  a| 
儲存驅動程式名稱
 a| 
`ontap-nas`、、 `ontap-san` `ontap-nas-economy`
`ontap-nas-flexgroup`、 `solidfire-san`



| `storagePrefix`  a| 
Volume名稱的選用首碼。預設值： `netappdvp_`。
 a| 
`staging_`



| `limitVolumeSize`  a| 
Volume大小的選擇性限制。預設： "" （未強制執行）
 a| 
`10g`

|===

TIP: 請勿將（包括預設值）用於 `storagePrefix`元素後端。根據預設、 `solidfire-san`驅動程式會忽略此設定、而不使用前置碼。我們建議使用特定的TenantId進行Docker Volume對應、或是使用Docker版本、驅動程式資訊和原始名稱填入的屬性資料、以便在可能使用任何名稱標示的情況下使用。

您可以使用預設選項、避免在每個建立的Volume上指定這些選項。此 `size`選項適用於所有控制器類型。如ONTAP 需如何設定預設Volume大小的範例、請參閱「功能區組態」一節。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| `size`  a| 
新磁碟區的選用預設大小。預設： `1G`
 a| 
`10G`

|===


== ONTAP 組態

除了上述全域組態值之外、使用ONTAP 時還提供下列頂層選項。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| `managementLIF`  a| 
IP位址ONTAP ：您可以指定完整網域名稱（FQDN）。
 a| 
`10.0.0.1`



| `dataLIF`  a| 
傳輸協定LIF的IP位址。

* ONTAP NAS 驅動程式 * ：建議您指定 `dataLIF`。如果未提供、Astra Trident會從SVM擷取資料lifs。您可以指定要用於NFS掛載作業的完整網域名稱（FQDN）、讓您建立循環配置資源DNS、以便在多個資料生命期之間達到負載平衡。

*《SAN驅動程式*：請勿指定用於iSCSI》ONTAP 。Astra Trident 使用link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["可選擇的LUN對應ONTAP"^]來探索建立多重路徑工作階段所需的 iSCI 生命。如果明確定義、就會產生警告 `dataLIF`。
 a| 
`10.0.0.2`



| `svm`  a| 
要使用的儲存虛擬機器（如果管理LIF是叢集LIF、則為必要）
 a| 
`svm_nfs`



| `username`  a| 
連線至儲存設備的使用者名稱
 a| 
`vsadmin`



| `password`  a| 
連線至儲存設備的密碼
 a| 
`secret`



| `aggregate`  a| 
用於資源配置的Aggregate（選用；如果已設定、則必須指派給SVM）。對於 `ontap-nas-flexgroup`驅動程式、此選項會被忽略。指派給SVM的所有集合體均可用來配置FlexGroup 一個SVolume。
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
如果使用率高於此百分比、則可選用、失敗的資源配置
 a| 
`75%`



| `nfsMountOptions`  a| 
精細控制NFS掛載選項；預設為「-o nfsver=3」。* 僅適用於 `ontap-nas`和 `ontap-nas-economy`驅動程式 * 。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["請參閱此處的NFS主機組態資訊"^]。
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Astra Trident 會以 `netappdvp`建立和管理每個節點 `igroups`。

此值不可變更或省略。

* 僅適用於 `ontap-san`驅動程式 * 。
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
可要求的最大磁碟區大小。
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
每FlexVol 個邊區最多qtree數、範圍必須為[50、300]、預設值為200。

* 對於 `ontap-nas-economy`驅動程序，此選項允許自定義每個 FlexVol 的 qtree 的最大數量 * 。
 a| 
`300`



| `sanType` | * 僅支援 `ontap-san`驅動程式。 *用於選擇 `iscsi` iSCSI 或 `nvme` NVMe / TCP 。 | `iscsi`如果空白 


| `limitVolumePoolSize` | * `ontap-san-economy` `ontap-san-economy` 僅支援和驅動程式。 *在 ONTAP ONTAP NAS 經濟型和 ONTAP SAN 經濟型驅動程式中限制 FlexVol 大小。  a| 
`300g`

|===
您可以使用預設選項、避免在您建立的每個Volume上指定這些選項：

[cols="1,3,2"]
|===
| 選項 | 說明 | 範例 


| `spaceReserve`  a| 
空間保留模式； `none`（精簡配置）或 `volume`（粗）
 a| 
`none`



| `snapshotPolicy`  a| 
要使用的 Snapshot 原則、預設為 `none`
 a| 
`none`



| `snapshotReserve`  a| 
Snapshot 保留百分比、預設為「」接受 ONTAP 預設值
 a| 
`10`



| `splitOnClone`  a| 
建立複本時、將其父複本分割成預設值 `false`
 a| 
`false`



| `encryption`  a| 
在新磁碟區上啟用 NetApp Volume Encryption （ NVE ）；預設為 `false`。必須在叢集上授權並啟用NVE、才能使用此選項。

如果在後端啟用NAE、則Astra Trident中配置的任何磁碟區都會啟用NAE。

如需更多資訊、請參閱link:../trident-reco/security-reco.html["Astra Trident如何與NVE和NAE搭配運作"]：。
 a| 
是的



| `unixPermissions`  a| 
NAS 選項適用於已佈建的 NFS 磁碟區、預設為 `777`
 a| 
`777`



| `snapshotDir`  a| 
用於存取目錄的 NAS 選項 `.snapshot`、預設為 `false`
 a| 
`true`



| `exportPolicy`  a| 
NFS 匯出原則使用的 NAS 選項、預設為 `default`
 a| 
`default`



| `securityStyle`  a| 
NAS選項、可存取已配置的NFS Volume。

NFS 支援 `mixed`和 `unix`安全樣式。預設值為 `unix`。
 a| 
`unix`



| `fileSystemType`  a| 
SAN 選項可選擇檔案系統類型、預設為 `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
要使用的分層原則、預設值為 `none`； `snapshot-only`適用於 ONTAP 9 前的 SVM-DR 組態
 a| 
`none`

|===


=== 擴充選項

 `ontap-nas`和 `ontap-san`驅動程式會為每個 Docker Volume 建立 ONTAP FlexVol 。支援每個叢集節點最多1000個FlexVols、叢集最多12、000個FlexVols。ONTAP如果您的 Docker Volume 需求符合這項限制、則 `ontap-nas`由於 FlexVols 提供的其他功能（例如 Docker Volume 精細快照和複製）、驅動程式是首選的 NAS 解決方案。

如果您需要的 Docker 磁碟區數量超過 FlexVol 限制所能容納的數量、請選擇 `ontap-nas-economy`或 `ontap-san-economy`驅動程式。

此 `ontap-nas-economy`驅動程式會在自動管理的 FlexVols 資源池中建立 Docker Volume 做為 ONTAP qtree 。qtree的擴充能力大幅提升、每個叢集節點最多可達100、000個、每個叢集最多可達2、400、000個、而犧牲了部分功能。此 `ontap-nas-economy`驅動程式不支援 Docker Volume 精細快照或複製。


NOTE: Docker swarm 目前不支援此 `ontap-nas-economy`驅動程式、因為 swarm 不會在多個節點之間協調磁碟區建立。

驅動程式會 `ontap-san-economy`在自動管理的 FlexVols 共用資源池中、將 Docker 磁碟區建立為 ONTAP LUN 。如此FlexVol 一來、每個支援不只侷限於一個LUN、而且能為SAN工作負載提供更好的擴充性。根據儲存陣列的不同、ONTAP 每個叢集最多可支援16384個LUN。由於磁碟區是下方的LUN、因此此驅動程式支援Docker磁碟區精細快照和複製。

選擇 `ontap-nas-flexgroup`驅動程式來增加單一磁碟區的平行度、使其可擴充至數十億個檔案的 PB 範圍。FlexGroups的一些理想使用案例包括AI / ML / DL、Big Data和分析、軟體建置、串流、檔案儲存庫等。Trident在配置FlexGroup 完一套SVM時、會使用指派給SVM的所有集合體。支援Trident也有下列考量：FlexGroup

* 需要ONTAP 9.2版或更新版本。
* 截至本文撰寫時、FlexGroups僅支援NFS v3。
* 建議啟用SVM的64位元NFSv3識別碼。
* 建議的 FlexGroup 成員 / 磁碟區大小下限為 100GiB 。
* 不支援FlexGroup 將複製複製用於實體磁碟區。


有關適用於 FlexGroups 的 FlexGroups 和工作負載的資訊、請參閱 https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup 《NetApp》《最佳實務做法與實作指南》"^]。

若要在同一個環境中取得進階功能和龐大規模、您可以使用執行多個 Docker Volume 外掛程式執行個體、其中一個使用、另 `ontap-nas-economy`一個使用 `ontap-nas`。



=== 範例ONTAP ：功能組態檔

.<code> ONTAP - 同級 </code> 驅動程式的 NFS 範例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.<code> ONTAP NAS FlexGroup </code> 驅動程式的 NFS 範例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.<code> ONTAP NAS 經濟型 </code> 驅動程式的 NFS 範例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
====
.<code> ONTAP 卡式 </code> 驅動程式的 iSCSI 範例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.<code> ONTAP SAN 經濟型 </code> 驅動程式的 NFS 範例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.適用於 <code> ONTAP 型 </code> 驅動程式的 NVMe / TCP 範例
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username":"vsadmin",
  "password":"password",
  "sanType": "nvme",
  "useREST": true
}
----
====


== 元件軟體組態

除了全域組態值之外、使用Element軟體（NetApp HCI / SolidFire）時、也可使用這些選項。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| `Endpoint`  a| 
https ： <login> ： <password> ： <mvip> / json <element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
iSCSI IP位址和連接埠
 a| 
10.0.0.7：3260



| `TenantName`  a| 
要使用的SolidFireF租戶（如果找不到、請建立）
 a| 
`docker`



| `InitiatorIFace`  a| 
將iSCSI流量限制為非預設介面時、請指定介面
 a| 
`default`



| `Types`  a| 
QoS規格
 a| 
請參閱以下範例



| `LegacyNamePrefix`  a| 
升級版Trident安裝的首碼。如果您使用 1.3.2 之前的 Trident 版本、並使用現有的 Volume 執行升級、則必須設定此值、才能存取透過 Volume 名稱方法對應的舊 Volume 。
 a| 
`netappdvp-`

|===
 `solidfire-san`驅動程式不支援 Docker swarm 。



=== 元素軟體組態檔範例

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----